### List Tasks
GET http://localhost:8091/tasks
Content-Type: application/json

> {%
    client.test("Response status is OK", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });

    client.test("Response has 15 elements", function() {
        client.assert(response.body.length === 15, `Expected 15 elements, but got ${response.body.length}`);
    });
%}

### List Labels
GET http://localhost:8091/labels
Content-Type: application/json

> {%
    client.test("Response status is OK", function() {
        client.assert(response.status === 200, "Response status is not 200");
    });
    client.test("Response has 3 elements", function() {
        client.assert(response.body.length=== 3, `Expected 3 elements, but got ${response.body.length}`);
    });
%}
