server:
  port: 8091
spring:
  application:
    name: todo
  datasource:
    driver-class-name: org.h2.Driver
    username: MARCIN
    password: MARCIN1
    url: "jdbc:h2:mem:mytodo;DB_CLOSE_ON_EXIT=FALSE"

  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop


