-- Inserting labels
INSERT INTO Label (NAME) VALUES ('HOME');
INSERT INTO Label (NAME) VALUES ('WORK');
INSERT INTO Label (NAME) VALUES ('HOUSEHOLD');

-- Inserting tasks
INSERT INTO Task (NAME, DESCRIPTION, COMPLETION, LABEL_ID) VALUES ('Task :1', 'Description for Task 1', FALSE, 1);
INSERT INTO Task (NAME, DESCRIPTION, COMPLETION, LABEL_ID) VALUES ('Task :2', 'Description for Task 2', FALSE, 1);
INSERT INTO Task (NAME, DESCRIPTION, COMPLETION, LABEL_ID) VALUES ('Task :3', 'Description for Task 3', FALSE, 1);
INSERT INTO Task (NAME, DESCRIPTION, COMPLETION, LABEL_ID) VALUES ('Task :4', 'Description for Task 4', FALSE, 1);
INSERT INTO Task (NAME, DESCRIPTION, COMPLETION, LABEL_ID) VALUES ('Task :5', 'Description for Task 5', FALSE, 1);

INSERT INTO Task (NAME, DESCRIPTION, COMPLETION, LABEL_ID) VALUES ('Task :6', 'Description for Task 6', FALSE, 2);
INSERT INTO Task (NAME, DESCRIPTION, COMPLETION, LABEL_ID) VALUES ('Task :7', 'Description for Task 7', FALSE, 2);
INSERT INTO Task (NAME, DESCRIPTION, COMPLETION, LABEL_ID) VALUES ('Task: 8', 'Description for Task 8', FALSE, 2);
INSERT INTO Task (NAME, DESCRIPTION, COMPLETION, LABEL_ID) VALUES ('Task: 9', 'Description for Task 9', FALSE, 2);
INSERT INTO Task (NAME, DESCRIPTION, COMPLETION, LABEL_ID) VALUES ('Task: 10', 'Description for Task 10', FALSE, 2);

INSERT INTO Task (NAME, DESCRIPTION, COMPLETION, LABEL_ID) VALUES ('Task: 11', 'Description for Task 11', FALSE, 3);
INSERT INTO Task (NAME, DESCRIPTION, COMPLETION, LABEL_ID) VALUES ('Task: 12', 'Description for Task 12', FALSE, 3);
INSERT INTO Task (NAME, DESCRIPTION, COMPLETION, LABEL_ID) VALUES ('Task: 13', 'Description for Task 13', FALSE, 3);
INSERT INTO Task (NAME, DESCRIPTION, COMPLETION, LABEL_ID) VALUES ('Task: 14', 'Description for Task 14', FALSE, 3);
INSERT INTO Task (NAME, DESCRIPTION, COMPLETION, LABEL_ID) VALUES ('Task: 15', 'Description for Task 15', FALSE, 3);
