# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: build-and-test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B install --file pom.xml



  build2:
            runs-on: ubuntu-latest
            permissions:
              pull-requests: write
            steps:
              - uses: actions/checkout@v4

              - name: Set up JDK 17
                uses: actions/setup-java@v3
                with:
                  java-version: '17'
                  distribution: 'temurin'

              - name: Run Coverage
                run: mvn clean verify

              - name: Add coverage to PR
                id: jacoco
                uses: madrapps/jacoco-report@v1.6.1
                with:
                  paths: |
                    ${{ github.workspace }}/target/site/jacoco/jacoco.xml
                  token: ${{ secrets.GITHUB_TOKEN }}
                  min-coverage-overall: 40
                  min-coverage-changed-files: 60
              - name: Display coverage overall
                run: |
                      echo "Coverage Overall - ${{ steps.jacoco.outputs.coverage-overall }}"
                      echo "The total coverage of all changed files - ${{ steps.jacoco.outputs.coverage-changed-files }}"
              - name: List files in target/site/jacoco
                run: ls -l target/site/jacoco

  publish-snapshot:
      needs: build
      runs-on: ubuntu-latest

      steps:
      - uses: actions/checkout@v4

      - name: Set up settings.xml for GitHub Packages
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Publish SNAPSHOT version to GitHub Packages
        run: mvn -B --no-transfer-progress deploy -DskipTests
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

